jobs:
  build:
    docker:
      - image: ruby:2.3.1
        environment:
          - PG_HOST=localhost
          - PG_USER=ubuntu
          - ENV: "CI"
      - image: postgres:9.5
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=db_name
    branches:
      only:
        - master
    steps:
      - run: make test
      - run: make
