# CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5-browsers
      - image: circleci/python:2.7.13
        environment:
          ENV: UnitTest
      - image: circleci/mysql:5.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies for client
          command: |
            npm install -g @angular/cli
            cd client
            npm install

      - run:
          name: run unit test
          command: |
            ng test
