# CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
        environment:
          ENV: UnitTest
      - image: circleci/node:8.5-browsers
      - image: circleci/mysql:5.7

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies for client
          command: |
            cd client
            npm install

      - run:
          name: install dependencies for server
          command: |
            virtualenv --no-site-packages .
            source bin/activate
            pip install -r server/requirements.txt
