version: 2
jobs:
  build:
    working_directory: ~/todos
    docker:
      - image: circleci/node:8.5-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "client/yarn.lock" }}
      - run:
          name: install-dependencies
          command: |
            cd client
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "client/yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./client/node_modules
      - run:
          name: angular-build
          command: |
            cd client
            yarn ng -- build --env=prod --no-progress
      - run:
          name: angular-test
          command: |
            cd client
            yarn test -- --single-run --no-progress --code-coverage --reporters=junit,coverage-istanbul
      - store_artifacts:
          path: client/coverage
          path: client/reports/unit
          prefix: tests
      - run:
          name: angular-lint
          command: |
            cd client
            yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      - store_artifacts:
          path: client/tslint.xml
          prefix: lint
